### ISSUE TITLE
No longer builds with LibreSSL 3.9.1

### ISSUE THREAD

**Issue by ekscrypto** [build-xcframeworks/libressl#2]
Followed the Readme instructions
* create ~/test folder
* cd into ~/test folder
* git clone https://github.com/build-xcframeworks/libressl
* cd into ~/test/libressl
* LIBRESSL=3.9.1 bash libressl.sh

Expected: successful build

Actual output:
```
...
  CC       libcrypto_la-crypto_lock.lo
In file included from crypto_lock.c:22:
./crypto_internal.h:41:9: error: call to undeclared function 'be32toh'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        return be32toh(v);
               ^
./crypto_internal.h:54:6: error: call to undeclared function 'htobe32'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        v = htobe32(v);
            ^
./crypto_internal.h:72:9: error: call to undeclared function 'be64toh'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        return be64toh(v);
               ^
./crypto_internal.h:85:6: error: call to undeclared function 'htobe64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        v = htobe64(v);
            ^
./crypto_internal.h:103:9: error: call to undeclared function 'le32toh'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        return le32toh(v);
               ^
./crypto_internal.h:116:6: error: call to undeclared function 'htole32'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        v = htole32(v);
            ^
```

**Comment by niklassaers** [comment]
New commit in place with support for 4.3.2
